apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: dev-

images:
  - name: ghcr.io/jkaminska2/tasks-backend
    newTag: dev
  - name: ghcr.io/jkaminska2/tasks-worker
    newTag: dev