apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: tasks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: wait-for-db-and-redis
          image: postgres:16
          envFrom:
            - configMapRef:
                name: app-config
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL..."
              until pg_isready -h "$DB_HOST" -p $DB_PORT; do sleep 2; done
              echo "Waiting for Redis..."
              until nc -z "$REDIS_HOST" "$REDIS_PORT"; do sleep 2; done
      containers:
        - name: worker
          image: ghcr.io/jkaminska2/tasks-worker:latest
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - exit 0
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exit 0
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"